/**
 * SOLIDIFIED TYPE DATABASE (AUTO-GENERATED)
 *
 * This file is managed by the 'xalor' transformer.
 * It maps your string-based keys back to their original TypeScript interfaces,
 * enabling ambient autocompletion and type safety across your entire project
 * without manual imports.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes will be overwritten during the next build/sync.
 */
declare module '@bgskinner2/xalor' {
  // The Miner will inject overloads here, for example:
  // export function getSolid(key: 'USER'): IUser;
}

export {};
