// ------------------------------------------------------------------------
// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by scripts/generate-configs.ts
// ------------------------------------------------------------------------

import { ObjectUtils } from '../utils';
import type { TUnique } from '../types';

/**
 * MASTER GENERATOR MODES CONFIGURATION
 * @note AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 */
export const GENERATOR_MODE_TRIGGERS = [
  'xalor.default',
  'xalor.mock',
  'xalor.clone',
  'xalor.cast',
] as const;

/**
 * MASTER REGISTER MODES CONFIGURATION
 * @note AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 */
export const REGISTER_MODE_TRIGGERS = ['xalor.register'] as const;

/**
 * MASTER TRANSFORM MODES CONFIGURATION
 * @note AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 */
export const TRANSFORM_MODE_TRIGGERS = [
  'xalor.pick',
  'xalor.omit',
  'xalor.merge',
  'xalor.flatten',
] as const;

/**
 * MASTER VALIDATION MODES CONFIGURATION
 * @note AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 */
export const VALIDATION_MODE_TRIGGERS = [
  'xalor.guard',
  'xalor.assert',
  'xalor.parse',
  'xalor.parseAsync',
  'xalor.audit',
] as const;

/**
 * SENTRY_TRIGGER_NAMES
 * Complete identifier matrix used by the compiler's static analysis layers.
 */
const RAW_SENTRY_TRIGGER_NAMES = [
  ...GENERATOR_MODE_TRIGGERS,
  ...REGISTER_MODE_TRIGGERS,
  ...TRANSFORM_MODE_TRIGGERS,
  ...VALIDATION_MODE_TRIGGERS,
] as const;

export const SENTRY_TRIGGER_NAMES = RAW_SENTRY_TRIGGER_NAMES satisfies TUnique<
  typeof RAW_SENTRY_TRIGGER_NAMES
>;

/**
 * SENTRY_TRIGGER_MODES
 * Strategy taxonomy groupings partitioning tokens into operational buckets.
 */
export const SENTRY_TRIGGER_MODES = {
  generatorXalor: GENERATOR_MODE_TRIGGERS,
  transformXalor: TRANSFORM_MODE_TRIGGERS,
  validationXalor: VALIDATION_MODE_TRIGGERS,
};

export const RUNTIME_TRIGGER_NAMES = ObjectUtils.keys(SENTRY_TRIGGER_MODES);

/**
 * RAW GENERATOR STRATEGY SPECIFICATION MODES
 * @note AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 */
export const GENERATOR_MODES = ['default', 'mock', 'clone', 'cast'] as const;

/**
 * RAW REGISTER STRATEGY SPECIFICATION MODES
 * @note AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 */
export const REGISTER_MODES = ['register'] as const;

/**
 * RAW TRANSFORM STRATEGY SPECIFICATION MODES
 * @note AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 */
export const TRANSFORM_MODES = ['pick', 'omit', 'merge', 'flatten'] as const;

/**
 * RAW VALIDATION STRATEGY SPECIFICATION MODES
 * @note AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 */
export const VALIDATION_MODES = [
  'guard',
  'assert',
  'parse',
  'parseAsync',
  'audit',
] as const;
