// ------------------------------------------------------------------------
// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by scripts/generate-configs.ts
// ------------------------------------------------------------------------

import * as constants from './constants';

export type TGeneratorTriggers =
  (typeof constants.GENERATOR_MODE_TRIGGERS)[number];

/**
 * TGeneratorXalorModes
 *
 * Generator List Modes
 *
 * @see {@link FoundationalTypesDocs.TGeneratorXalorModes}
 */
export type TGeneratorXalorModes = (typeof constants.GENERATOR_MODES)[number];

export type TMatchTriggers = (typeof constants.MATCH_MODE_TRIGGERS)[number];

/**
 * TMatchXalorModes
 *
 * Match List Modes
 *
 * @see {@link FoundationalTypesDocs.TMatchXalorModes}
 */
export type TMatchXalorModes = (typeof constants.MATCH_MODES)[number];

export type TRegisterTriggers =
  (typeof constants.REGISTER_MODE_TRIGGERS)[number];

/**
 * TRegisterXalorModes
 *
 * Register List Modes
 *
 * @see {@link FoundationalTypesDocs.TRegisterXalorModes}
 */
export type TRegisterXalorModes = (typeof constants.REGISTER_MODES)[number];

export type TTransformTriggers =
  (typeof constants.TRANSFORM_MODE_TRIGGERS)[number];

/**
 * TTransformXalorModes
 *
 * Transform List Modes
 *
 * @see {@link FoundationalTypesDocs.TTransformXalorModes}
 */
export type TTransformXalorModes = (typeof constants.TRANSFORM_MODES)[number];

export type TValidationTriggers =
  (typeof constants.VALIDATION_MODE_TRIGGERS)[number];

/**
 * TValidationXalorModes
 *
 * Validation List Modes
 *
 * @see {@link FoundationalTypesDocs.TValidationXalorModes}
 */
export type TValidationXalorModes = (typeof constants.VALIDATION_MODES)[number];

/**
 * Comprehensive master matrix of all valid trigger tokens.
 */
export type TSentryTriggerNames =
  (typeof constants.SENTRY_TRIGGER_NAMES)[number];

/**
 * Comprehensive master matrix of all valid parent execution runtime trigger category keys.
 */
export type TRuntimeTriggerName =
  (typeof constants.RUNTIME_TRIGGER_NAMES)[number];
