import type { TMessageHandlerParams } from '../types';
import { IS_SOLID_CONFIG_ITEMS } from '../constants';
import { ObjectUtils } from '../utils';

export const XALOR_MESSAGE_HANDLER = {
  ERROR: {
    // --- COMPILER & REIFIER TOOLCHAIN FAILURES (BUILD TIME) ---
    UNSUPPORTED_KIND: (props: TMessageHandlerParams) =>
      `[xalor:compiler] Unsupported shape kind: "${props.kind}". This usually happens if the metadata was generated by an incompatible version.`,

    DATABASE_VERSION_MISMATCH: (props: TMessageHandlerParams) =>
      `[xalor:engine] Version mismatch for "${props.key}". Expected framework version ${IS_SOLID_CONFIG_ITEMS.solidVersion}, but received cache version ${props.version}.`,

    COLLISION: (props: TMessageHandlerParams) =>
      `[xalor:registry] 🚨 Collision! Key "${props.key}" is already registered in active memory. Context: ${props.msg}`,

    DEFINITION_COLLISION: (props: TMessageHandlerParams) =>
      `[xalor:compiler] 🚨 Duplicate Type Definition! The key "${props.key}" was mined in separate locations:\n  ➔ 1. ${props.path}\n  ➔ 2. ${props.location}`,

    // --- STRUCTURAL PERSISTENCE & CACHE FAILURES (HOT RELOAD) ---
    MISSING_VAULT_BLUEPRINT: (props: TMessageHandlerParams) =>
      `[xalor:sync] Blueprint metadata missing for key "${props.key}", though its storage manifest entry exists at ${props.location}.`,

    MISSING_VAULT_KEY: (props: TMessageHandlerParams) =>
      `[xalor:vault] Ambient lookup failed: The key "${props.key}" is completely unknown to the Vault registry. Ensure this type is actively mined by the transformer.`,

    BROKEN_PIPE_GENESIS: (props: TMessageHandlerParams) =>
      `[xalor:persist] Process boundary synchronization failure: Failed to write Genesis Cache metadata. System Error: ${props.error}`,

    // --- SCHEMA INGRESS VALIDATION ANOMALIES (RUNTIME APIS) ---
    TYPE_MISMATCH: (props: TMessageHandlerParams) =>
      `[xalor:bouncer] Type verification rejection at path "${props.path}": Expected primitive layout "${props.expected}", but received "${props.received}".`,

    LITERAL_MISMATCH: (props: TMessageHandlerParams) =>
      `[xalor:bouncer] Literal exact value rejection at path "${props.path}": Expected the strict scalar constraint value: "${props.expected}", but received "${props.received}".`,

    MISSING_KEY: (props: TMessageHandlerParams) =>
      `[xalor:bouncer] Structural property validation failure: Required layout key property "${props.path}" is missing or undefined inside incoming input payload.`,

    UNION_FAIL: (props: TMessageHandlerParams) =>
      `[xalor:bouncer] Isolated choice matrix drop: Input data payload structural state at path "${props.path}" failed to solidify against any allowed variant union branches.`,
    INTERNAL_FRAMEWORK_ERROR: (props: TMessageHandlerParams) =>
      `[xalor:critical] An unhandled or unknown framework disruption occurred. Code: "${props.key}". Context: ${props.msg}`,
  } as const,

  WARNING: {
    COLLISION: (props: TMessageHandlerParams) =>
      `[xalor:registry] ⚠️ Collision warning! Key "${props.key}" is already defined in the active registry stack. Overwriting existing layout metadata mapping inline.`,

    DEPRECATED_ACCESS: () =>
      `[xalor:api] ⚠️ API Lifecycle Warning: Direct access to the internal 'items' lookup map parameter layout is deprecated. Please update hooks to reference 'blueprints' or 'manifest' instead.`,
  } as const,
};

/* prettier-ignore */ export const XALOR_ERROR_MESSAGE_KEYS = ObjectUtils.keys(XALOR_MESSAGE_HANDLER.ERROR);
/* prettier-ignore */ export const XALOR_WARNING_MESSAGE_KEYS = ObjectUtils.keys(XALOR_MESSAGE_HANDLER.WARNING);
