import ts from 'typescript';
import {
  isUndefined,
  isKeyInObject,
  isArray,
  isNull,
  isObject,
} from '../../../shared';
import { TypeFlags } from 'typescript';
import type { CallExpression, Type, TypeChecker } from 'typescript';
import { errorReportService } from '../../../shared/error';
import type { TTypeGuardErrorFailure } from '../../../shared/error';
import { shapeKindUtilsService } from '../../../shared/service';
import { isTypeRecursive } from '../sentry-layer';
import { isAmbientPlatformType, isObjectTypeGuard } from '../../utils/guards';
import {
  isNodeInsideGenericScope,
  hasMappedTemplateModifiers,
} from './helpers';

/**
 * RULE: ONE
 *
 * ROLE:
 * Serves as the authoritative vanguard checkpoint of the compiler gatehouse. It
 * enforces structural parameter boundaries by intercepting abstract, uninstantiated
 * type arguments or dynamic invocation call sites before they can enter the reifier
 * pipeline or breach memory isolation structures.
 *
 */
export function verifyUnboundGenericCompliance(
  flags: TypeFlags,
  keyName: string,
  callNode?: CallExpression,
): TTypeGuardErrorFailure | undefined {
  /* prettier-ignore */ const typeResolverRuleMapper = errorReportService.getAreaErrorMapper('TRANSFORMER_TYPE_RESOLVER');
  if (isNodeInsideGenericScope(callNode)) {
    return {
      /* prettier-ignore */ rule: typeResolverRuleMapper.UNBOUND_GENERIC_PARAMETER.rule,
      /* prettier-ignore */ message: typeResolverRuleMapper.UNBOUND_GENERIC_PARAMETER.message(keyName) + ` (Aborted compilation to protect printer: Call site resides inside an unresolved generic context scope)`,
    };
  }
  if ((flags & TypeFlags.TypeParameter) !== 0) {
    return {
      /* prettier-ignore */ rule: typeResolverRuleMapper.UNBOUND_GENERIC_PARAMETER.rule,
      /* prettier-ignore */ message: typeResolverRuleMapper.UNBOUND_GENERIC_PARAMETER.message(keyName),
    };
  }

  return undefined;
}

/**
 * RULE: TWO
 *
 * ROLE IN ARCHITECTURE:
 * Acts as the centralized metaprogramming validation gate. It intercepts unresolved
 * evaluation instructions, deferred logical branches, and token transformation states
 * that are syntactically valid within TypeScript's type programming system but impossible
 * to serialize into static metadata graphs.
 *
 */
export function verifyDeferredResolutionCompliance(
  type: Type,
  flags: TypeFlags,
  keyName: string,
): TTypeGuardErrorFailure | undefined {
  const typeResolverRuleMapper = errorReportService.getAreaErrorMapper(
    'TRANSFORMER_TYPE_RESOLVER',
  );

  if ((flags & TypeFlags.Conditional) !== 0) {
    // Intercept deferred generic mapped template string mutations before they trigger a generic failure
    if (isKeyInObject('templateFlags')(type) || isKeyInObject('target')(type)) {
      return {
        /* prettier-ignore */ rule: typeResolverRuleMapper.UNSUPPORTED_MAPPED_TYPE_MODIFIER.rule,
        /* prettier-ignore */ message: typeResolverRuleMapper.UNSUPPORTED_MAPPED_TYPE_MODIFIER.message(keyName, 'Deferred Generic Mapped Template'),
      };
    }

    return {
      /* prettier-ignore */ rule: typeResolverRuleMapper.UNBOUND_GENERIC_CONDITIONAL.rule,
      /* prettier-ignore */ message: typeResolverRuleMapper.UNBOUND_GENERIC_CONDITIONAL.message(keyName),
    };
  }

  // Root-Level Unbound Indexed Access (T[K]) Layouts
  if ((flags & TypeFlags.IndexedAccess) !== 0) {
    return {
      /* prettier-ignore */ rule: typeResolverRuleMapper.UNBOUND_INDEX_ACCESS_LOOKUP.rule,
      /* prettier-ignore */ message: typeResolverRuleMapper.UNBOUND_INDEX_ACCESS_LOOKUP.message(keyName),
    };
  }

  const SubstitutionFlagBit = 1 << 26;
  if ((flags & SubstitutionFlagBit) !== 0) {
    return {
      /* prettier-ignore */ rule: typeResolverRuleMapper.UNSUPPORTED_MAPPED_TYPE_MODIFIER.rule,
      /* prettier-ignore */ message: typeResolverRuleMapper.UNSUPPORTED_MAPPED_TYPE_MODIFIER.message(keyName, 'Substitution Parameter Loop'),
    };
  }

  return undefined;
}

/**
 * RULE: THREE
 *
 * ROLE:
 * Inspects structural compilation boundaries and terminal type values. It catches
 * intrinsic compiler errors, infinite-depth utility collapses into 'any' nodes,
 * and root-level structural primitive contradictions (never).
 *
 */
export function verifyTerminalBoundaryCompliance(
  type: Type,
  flags: TypeFlags,
  keyName: string,
): TTypeGuardErrorFailure | undefined {
  const typeResolverRuleMapper = errorReportService.getAreaErrorMapper(
    'TRANSFORMER_TYPE_RESOLVER',
  );

  // Phase A: Audit TypeFlags.Any for Intrinsic Failures or Computational Collapses
  if ((flags & TypeFlags.Any) !== 0) {
    const symbol = type.getSymbol();

    // 1. If it represents an Intrinsic Error Node generated by broken syntax or missing files
    if (!symbol) {
      return {
        /* prettier-ignore */ rule: typeResolverRuleMapper.CATASTROPHIC_COMPILER_ERROR.rule,
        /* prettier-ignore */ message: typeResolverRuleMapper.CATASTROPHIC_COMPILER_ERROR.message(keyName),
      };
    }

    // 2. If it represents a complex type loop that exceeded compiler evaluation depth limits
    if (symbol.getName() !== 'any') {
      return {
        /* prettier-ignore */ rule: typeResolverRuleMapper.COMPUTATIONAL_COLLAPSE_ANY_NODE.rule,
        /* prettier-ignore */ message: typeResolverRuleMapper.COMPUTATIONAL_COLLAPSE_ANY_NODE.message(keyName),
      };
    }
  }

  // Phase B: Audit for Root Primitive Contradictions (e.g., string & number)
  if ((flags & TypeFlags.Never) !== 0) {
    return {
      /* prettier-ignore */ rule: typeResolverRuleMapper.TERMINAL_CONTRADICTION.rule,
      /* prettier-ignore */ message: typeResolverRuleMapper.TERMINAL_CONTRADICTION.message(keyName),
    };
  }

  return undefined;
}

/**
 * RULE: FOUR
 *
 * ROLE:
 * Enforces Xalor's pure data schema boundaries. It flags raw callable signatures,
 * construct layouts, and runtime dynamic ESSymbols, while typesafely passing authorized
 * built-in platform instances tracked in the registry.
 *
 */
export function verifyExecutableSignatureCompliance(
  type: Type,
  flags: TypeFlags,
  keyName: string,
): TTypeGuardErrorFailure | undefined {
  const typeResolverRuleMapper = errorReportService.getAreaErrorMapper(
    'TRANSFORMER_TYPE_RESOLVER',
  );

  const callSignatures = type.getCallSignatures();
  const constructSignatures = type.getConstructSignatures();

  if (
    callSignatures.length > 0 ||
    constructSignatures.length > 0 ||
    (flags & TypeFlags.ESSymbol) !== 0
  ) {
    const symbol = type.getSymbol() ?? type.aliasSymbol;
    const symbolName = symbol?.getName()?.replace(/Constructor$/, '');

    // Validate if the token matches a registered root-level 'instanceof' class block
    const isKnownInstance =
      symbolName && shapeKindUtilsService.isKnownInstanceKey(symbolName);

    if (!isKnownInstance) {
      return {
        /* prettier-ignore */ rule: typeResolverRuleMapper.UNSERIALIZABLE_EXECUTABLE.rule,
        /* prettier-ignore */ message: typeResolverRuleMapper.UNSERIALIZABLE_EXECUTABLE.message(keyName),
      };
    }
  }

  return undefined;
}
/**
 * RULE: FIVE
 *
 * ROLE:
 * Iterates through composite object layouts, unions, and intersections to trap
 * infinite cyclical dependency calculation loops before they pollute the registry.
 *
 */
export function verifyRecursiveGraphCompliance(
  type: Type,
  flags: TypeFlags,
  checker: TypeChecker,
  keyName: string,
): TTypeGuardErrorFailure | undefined {
  const typeResolverRuleMapper = errorReportService.getAreaErrorMapper(
    'TRANSFORMER_TYPE_RESOLVER',
  );

  if (
    (flags & (TypeFlags.Object | TypeFlags.Intersection | TypeFlags.Union)) !==
    0
  ) {
    if (!checker.isArrayType(type)) {
      const symbol = type.getSymbol() ?? type.aliasSymbol;
      const symbolName = symbol?.getName()?.replace(/Constructor$/, '');
      const isKnownInstance =
        symbolName && shapeKindUtilsService.isKnownInstanceKey(symbolName);

      if (!isAmbientPlatformType(type) && !isKnownInstance) {
        if (isTypeRecursive(type, checker)) {
          const aliasName = type.aliasSymbol
            ? type.aliasSymbol.getName()
            : 'Anonymous/Composite';
          return {
            /* prettier-ignore */ rule: typeResolverRuleMapper.COMPUTATIONAL_COLLAPSE_RECURSIVE_LOOP.rule,
            /* prettier-ignore */ message: typeResolverRuleMapper.COMPUTATIONAL_COLLAPSE_RECURSIVE_LOOP.message( keyName, aliasName),
          };
        }
      }
    }
  }

  return undefined;
}

/**
 * RULE: SIX
 *
 * ROLE:
 * Inspects structural object maps to catch dynamic template key re-mappings (as)
 * or open-ended unbound generic mapped modifiers that emit empty object blocks.
 *
 */
export function verifyMappedStructureCompliance(
  type: Type,
  checker: TypeChecker,
  keyName: string,
): TTypeGuardErrorFailure | undefined {
  const typeResolverRuleMapper = errorReportService.getAreaErrorMapper(
    'TRANSFORMER_TYPE_RESOLVER',
  );

  if (isObjectTypeGuard(type) && !checker.isArrayType(type)) {
    if ((type.objectFlags & ts.ObjectFlags.Mapped) !== 0) {
      const isUnboundGenericMappedType =
        checker.getPropertiesOfType(type).length === 0;

      // Clean, expressive assertion leveraging our new custom type guard
      if (hasMappedTemplateModifiers(type) || isUnboundGenericMappedType) {
        return {
          /* prettier-ignore */ rule: typeResolverRuleMapper.UNSUPPORTED_MAPPED_TYPE_MODIFIER.rule,
          /* prettier-ignore */ message: typeResolverRuleMapper.UNSUPPORTED_MAPPED_TYPE_MODIFIER.message(keyName, 'Dynamic/Unbound Mapped Template'),
        };
      }
    }
  }

  return undefined;
}
/**
 * RULE: SEVEN
 *
 * ROLE:
 * Sweeps array-like object definitions to ensure sequence boundaries are explicitly bounded.
 * Traps infinite or un-evaluated generic rest spread tails (...Args) directly from raw structural
 * blueprints to protect downstream printing and node compilation pipelines.
 *
 */
export function verifyTupleSequenceCompliance(
  type: Type,
  checker: TypeChecker,
  keyName: string,
): TTypeGuardErrorFailure | undefined {
  const typeResolverRuleMapper = errorReportService.getAreaErrorMapper(
    'TRANSFORMER_TYPE_RESOLVER',
  );

  if (isObjectTypeGuard(type) && checker.isArrayType(type)) {
    if ((type.objectFlags & ts.ObjectFlags.Tuple) !== 0) {
      /* prettier-ignore */
      if ( isKeyInObject('target')(type) && !isNull(type.target) && isObject(type.target)) {
        const targetObj = type.target;
        /* prettier-ignore */
        if (isKeyInObject('typeArguments')(targetObj) && isArray(targetObj.typeArguments)) {
          // Cast narrowed cleanly using standard import configurations to satisfy Commandment IX
         const argsArray = targetObj.typeArguments as Type[];

          for (let i = 0; i < argsArray.length; i++) {
            const arg = argsArray[i];
            if (isUndefined(arg)) continue;

            const argFlags = arg.getFlags();
            const SubstitutionBit = 1 << 26;

            if (
              (argFlags & TypeFlags.TypeParameter) !== 0 ||
              (argFlags & SubstitutionBit) !== 0 ||
              arg.isTypeParameter()
            ) {
              return {
                /* prettier-ignore */   rule: typeResolverRuleMapper.UNRESOLVED_TUPLE_REST_VARIADIC.rule,
                /* prettier-ignore */   message:typeResolverRuleMapper.UNRESOLVED_TUPLE_REST_VARIADIC.message(keyName),
              };
            }
          }
        }
      }
    }
  }

  return undefined;
}

/**
 * RULE: EIGHT
 *
 * ROLE:
 * Performs an absolute structural audit on properties and indexers. Step A flattens and sweeps
 * child sub-nodes to trap nested un-evaluated lookup parameters (T[K]). Step B ensures index schemas
 * contain explicit key configurations, protecting registry data integrity maps.
 *
 */
export function verifyPropertyLayoutCompliance(
  type: Type,
  flags: TypeFlags,
  checker: TypeChecker,
  keyName: string,
): TTypeGuardErrorFailure | undefined {
  const typeResolverRuleMapper = errorReportService.getAreaErrorMapper(
    'TRANSFORMER_TYPE_RESOLVER',
  );

  if (
    (flags & (TypeFlags.Object | TypeFlags.Intersection | TypeFlags.Union)) !==
    0
  ) {
    const coreProperties = checker.getPropertiesOfType(type);
    const indexInfos = checker.getIndexInfosOfType(type);

    // Phase A: Deep Property Security Scan
    for (let i = 0; i < coreProperties.length; i++) {
      const propSym = coreProperties[i];
      if (isUndefined(propSym)) continue;

      const propDecl =
        propSym.valueDeclaration ??
        (!isUndefined(propSym.declarations) && propSym.declarations.length > 0
          ? propSym.declarations[0]
          : undefined);
      if (isUndefined(propDecl)) continue;

      const propType = checker.getTypeOfSymbolAtLocation(propSym, propDecl);
      if (!isUndefined(propType)) {
        const propFlags = propType.getFlags();

        if (
          (propFlags & (TypeFlags.IndexedAccess | TypeFlags.TypeParameter)) !==
          0
        ) {
          return {
            /* prettier-ignore */ rule: typeResolverRuleMapper.UNBOUND_INDEX_ACCESS_LOOKUP.rule,
            /* prettier-ignore */ message: typeResolverRuleMapper.UNBOUND_INDEX_ACCESS_LOOKUP.message(keyName),
          };
        }
      }
    }

    // Phase B: Open Index Signature Verification
    if (coreProperties.length === 0 && indexInfos.length > 0) {
      return {
        rule: typeResolverRuleMapper.OPEN_INDEX_SIGNATURE.rule,
        message: typeResolverRuleMapper.OPEN_INDEX_SIGNATURE.message(keyName),
      };
    }
  }

  return undefined;
}
