import type { TRuntimeApiErrorRules } from '../types/error-types';

/**
 * ⚙️ RUNTIME_API_RULE_KEYS
 *
 * ROLE:
 * Defines runtime validation failure states encountered during schema enforcement.
 *
 * These rules occur when:
 * - runtime data violates structural contracts
 * - expected schema fields are missing or mismatched
 * - union/intersection constraints fail evaluation
 * - depth or traversal limits are exceeded
 *
 * NOTE:
 * These are execution-time errors (post-compilation validation layer).
 */
export const RUNTIME_API_RULE_KEYS = {
  MISSING_KEY_PRESENCE: 'missing_key_presence',
  MISSING_FROM_VAULT: 'missing_from_vault',
  PRIMITIVE_MISMATCH: 'primitive_mismatch',
  LITERAL_MISMATCH: 'literal_mismatch',
  INTERSECTION_BREACHED: 'intersection_breached',
  DEPTH_OVERFLOW: 'depth_overflow',
  UNION_EXHAUSTED: 'union_exhausted',
  EXCESS_PROPERTY: 'excess_property',
  MISSING_PROPERTY: 'missing_property',

  INVALID_KEY_FORMAT: 'invalid_key_format',
  FUNCTION_MISMATCH: 'function_mismatch',
  INSTANCE_MISMATCH: 'instance_mismatch',

  // Advanced Constraint Keys
  BRAND_CONSTRAINT_VIOLATION: 'brand_constraint_violation',
  FUNCTION_RETURNS_VIOLATION: 'function_returns_violation',
  COLLECTION_BOUNDS_EXCEEDED: 'collection_bounds_exceeded',
} as const;

/**
 * 🌊 XALOR_MATCH_DRIFT_RULE_KEYS
 *
 * ROLE:
 * Defines structural versioning and schema migration failure states.
 *
 * These rules occur in the matchXalorDrift system when:
 * - legacy payloads cannot be mapped to current schemas
 * - ancestral blueprint metadata is missing or invalid
 * - migration transformations violate target schema constraints
 * - compiled transformation infrastructure is unavailable
 *
 * NOTE:
 * This layer is responsible for backward-compatible schema evolution across system versions.
 */
export const XALOR_MATCH_DRIFT_RULE_KEYS = {
  MALFORMED_NON_RECORD_PAYLOAD: 'malformed_non_record_payload',
  ANCESTRAL_KEY_MISSING_FROM_VAULT: 'ancestral_key_missing_from_vault',
  UNEXPECTED_STREAM_COLLAPSE: 'unexpected_stream_collapse',
  MIGRATION_MUTATION_VIOLATION: 'migration_mutation_violation',
  MISSING_COMPILED_INFRASTRUCTURE: 'missing_compiled_infrastructure',
  // New keys mapped to Phase 1, Phase 2, and Phase 4 context functions:
  CURRENT_PHASE_VALIDATION_FAILED: 'current_phase_validation_failed',
  ANCESTRAL_TRANSFORM_TYPE_MISMATCH: 'ancestral_transform_type_mismatch',
  CIRCUIT_BREAKER_FALLBACK_INVALID: 'circuit_breaker_fallback_invalid',
  UNKNOWN_DRIFT_TOKEN: 'unknown_drift_token',
  DETACHED_COMPILER_METADATA: 'detached_compiler_metadata',
  DEFAULT_ERROR: 'default_error',
  STRICT_FALLBACK_VIOLATION: 'strict_fallback_violation',
  CUSTOM_FILL_OMISSION: 'custom_fill_omission',
  CUSTOM_FILL_VALIDATION_FAIL: 'custom_fill_validation_fail',
  MALFORMED_REGISTRY_KEYS: 'malformed_registry_keys',
  AUTOMATED_FILL_VALIDATION_FAIL: 'automated_fill_validation_fail',
} as const;

/**
 * 🪐 RUNTIME_API_MESSAGE_KEYWORD_RULES
 *
 * ROLE:
 * A high-speed, compile-time switchless keyword mapping registry that translates
 * raw diagnostic validation strings into deterministic runtime rule categories.
 *
 * STRATEGY:
 * Bypasses sequential procedural if/else branching, heavy dynamic regex scanning,
 * and switch metrics entirely. By anchoring known error keyword signatures directly
 * to target rule tags (e.g., 'depth' ──► 'depth_overflow') via an immutable, flat
 * tuple array dictionary, it guarantees a predictable, constant-time scan layout
 * across the execution stack frame.
 *
 * WHY:
 * Satisfies Commandment IV (Operation Isolation Rule) and Commandment VIII (Internal Efficiency).
 * It isolates raw validation text scanning mechanics away from the formatting and reporting
 * pipelines. This enables the engine to process low-level text errors generated by all 10
 * core TSolidShape AST variants with absolute zero heap memory allocations or runtime string
 * duplication overheads during active ingestion sweeps.
 *
 * INVARIANT:
 * Zero allocations inside hot paths. Elements must be carefully sorted so that highly
 * specific structural key phrases take positional precedence over broad fallback tokens.
 */

/* prettier-ignore */
export const RUNTIME_API_MESSAGE_KEYWORD_RULES: readonly (readonly [string, TRuntimeApiErrorRules])[] = [
  /* prettier-ignore */ ['depth', 'depth_overflow'],
  /* prettier-ignore */ ['maxdepth', 'depth_overflow'],
  /* prettier-ignore */ ['missing from vault', 'missing_from_vault'],
  /* prettier-ignore */ ['registered shape', 'missing_from_vault'],
  /* prettier-ignore */ ['missing_key_presence', 'missing_key_presence'],
  /* prettier-ignore */ ['missing blueprint', 'missing_key_presence'],
  /* prettier-ignore */ ['missing', 'missing_property'],
  /* prettier-ignore */ ['excess_property', 'excess_property'],
  /* prettier-ignore */ ['excess', 'excess_property'],
  /* prettier-ignore */ ['union', 'union_exhausted'],
  /* prettier-ignore */ ['intersection', 'intersection_breached'],
  /* prettier-ignore */ ['literal', 'literal_mismatch'],
  /* prettier-ignore */ ['invalid_key_format', 'invalid_key_format'],
  /* prettier-ignore */ ['pattern', 'invalid_key_format'],
  /* prettier-ignore */ ['parameters', 'function_mismatch'],
  /* prettier-ignore */ ['signature', 'function_mismatch'],
  /* prettier-ignore */ ['instanceof', 'instance_mismatch'],
  /* prettier-ignore */ ['resolveinstancector', 'instance_mismatch'],
  /* prettier-ignore */ ['brand', 'brand_constraint_violation'],
  /* prettier-ignore */ ['refinement', 'brand_constraint_violation'],
  /* prettier-ignore */ ['returntype', 'function_returns_violation'],
  /* prettier-ignore */ ['return', 'function_returns_violation'],
  /* prettier-ignore */ ['maxlength', 'collection_bounds_exceeded'],
  /* prettier-ignore */ ['minlength', 'collection_bounds_exceeded'],
  /* prettier-ignore */ ['tuple', 'collection_bounds_exceeded'],
] satisfies readonly (readonly [string, TRuntimeApiErrorRules])[];

export const RUNTIME_LOGGER_DESIGN_SPECTRUM = {
  red: '\x1b[31m',
  gray: '\x1b[90m',
  textLightRed: '\x1b[38;5;196m\x1b[1m',
  textLightGreen: '\x1b[38;5;82m\x1b[1m',
  bold: '\x1b[1m',
  cyan: '\x1b[36m',
  reset: '\x1b[0m',
} as const;

export const RUNTIME_SHAPE_VALIDATION_ERROR_KEYS = [
  'ARRAY_VALIDATION_TYPE_MISMATCH',
  'ARRAY_VALIDATION_MIN_LENGTH_VIOLATION',
  'OBJECT_VALIDATION_TYPE_MISMATCH',
  'OBJECT_VALIDATION_EXCESS_PROPERTY',
  'OBJECT_VALIDATION_MISSING_REQUIRED_KEY',
  'OBJECT_VALIDATION_MISSING_PROPERTY',
  'OBJECT_VALIDATION_UNDEFINED_PROPERTY',
  'UNION_VALIDATION_NO_MATCH',
  'REF_VALIDATION_MISSING_VAULT_ENTRY',
  'PRIMITIVE_VALIDATION_NULL_EXPECTED',
  'PRIMITIVE_VALIDATION_UNDEFINED_EXPECTED',
  'PRIMITIVE_VALIDATION_STRING_EXPECTED',
  'PRIMITIVE_VALIDATION_NUMBER_EXPECTED',
  'PRIMITIVE_VALIDATION_BOOLEAN_EXPECTED',
  'PRIMITIVE_VALIDATION_BIGINT_EXPECTED',
  'PRIMITIVE_VALIDATION_UNKNOWN_TYPE',
  'INTERSECTION_VALIDATION_PART_FAILED',
  'LITERAL_VALIDATION_VALUE_MISMATCH',
  'FUNCTION_VALIDATION_TYPE_MISMATCH',
  'FUNCTION_VALIDATION_PARAMETER_MISMATCH',
  'INSTANCEOF_VALIDATION_NIL_VALUE',
  'INSTANCEOF_VALIDATION_PROTOTYPE_MISMATCH',
  'ENGINE_FATAL_UNSUPPORTED_SHAPE_KIND',
] as const;

/**
 *  KEYED CONFIG LIBRARY FOR SIMULACRUM GENERATOR UTILS
 *
 * SIMULACRUM FOUNDATION:
 * Canonical configuration keys recognized by Simulacrum's generator engine.
 * Each key represents a declarative generation strategy and serves as the
 * stable contract between configuration objects and the corresponding
 * generation implementation.
 *
 * Rather than relying on hard-coded string literals throughout the codebase,
 * this registry provides a single immutable source of truth for all supported
 * generator identifiers, ensuring consistency, discoverability, and type
 * safety across the generation pipeline.
 *
 */
export const XALOR_SIM_GENERATOR_UTIL_KEYS = {
  uuid: 'pure',
  compactId: 'pure',
  percentage: 'pure',
  currency: 'pure',
  loremIpsum: 'pure',
  timestamp: 'pure',
  mockJwt: 'pure',
  email: 'contextual',
  userHandle: 'contextual',
  maskedString: 'transformer',
  miniBlockCipher: 'transformer',
} as const;
