import * as fs from 'fs';
import * as path from 'path';
import ts from 'typescript';

const PROJECT_ROOT = process.cwd();

/* prettier-ignore */ const XALOR_CORE_PATH = path.resolve(PROJECT_ROOT, 'src/api/index.ts');
/* prettier-ignore */ const OUTPUT_CONFIG_PATH = path.resolve(PROJECT_ROOT, 'shared/auto/constants.ts');
/* prettier-ignore */ const OUTPUT_TYPE_PATH = path.resolve(PROJECT_ROOT, 'shared/auto/types.ts');

function generateMasterConfig() {
  if (!fs.existsSync(XALOR_CORE_PATH)) {
    console.error(`❌ Source file missing: ${XALOR_CORE_PATH}`);
    process.exit(1);
  }

  const sourceCode = fs.readFileSync(XALOR_CORE_PATH, 'utf8');
  const sourceFile = ts.createSourceFile(
    XALOR_CORE_PATH,
    sourceCode,
    ts.ScriptTarget.Latest,
    true,
  );

  // 🎯 Dynamic Record Store: Scales automatically to any newly encountered category
  const categoryStore: Record<
    string,
    { rawModes: Set<string>; fullTriggers: Set<string> }
  > = {};
  let insideTargetClass = false;

  function visitor(node: ts.Node) {
    if (ts.isClassDeclaration(node) && node.name?.text === 'XalorCore') {
      insideTargetClass = true;
      ts.forEachChild(node, visitor);
      insideTargetClass = false;
      return;
    }

    if (insideTargetClass && ts.isMethodDeclaration(node)) {
      const fullText = sourceFile.getFullText();
      const ranges = ts.getLeadingCommentRanges(fullText, node.getFullStart());
      if (ranges) {
        let apiTagValue: string | null = null;
        let modeTagValue: string | null = null;

        for (const range of ranges) {
          const comment = fullText.substring(range.pos, range.end);
          const apiMatch = comment.match(/@Api\s+(\w+)/i);
          const modeMatch = comment.match(/@mode\s+(\w+)/i);

          if (apiMatch) apiTagValue = apiMatch[1].toLowerCase();
          if (modeMatch) modeTagValue = modeMatch[1];
        }

        if (apiTagValue && modeTagValue) {
          // 🚀 Dynamically allocate the category collections if seen for the first time
          if (!categoryStore[apiTagValue]) {
            categoryStore[apiTagValue] = {
              rawModes: new Set(),
              fullTriggers: new Set(),
            };
          }
          categoryStore[apiTagValue].rawModes.add(modeTagValue);
          categoryStore[apiTagValue].fullTriggers.add(`xalor.${modeTagValue}`);
        }
      }
    }
    ts.forEachChild(node, visitor);
  }

  ts.forEachChild(sourceFile, visitor);

  // Fallback anchor configuration for your register entry point
  if (!categoryStore['register']) {
    categoryStore['register'] = {
      rawModes: new Set(['register']),
      fullTriggers: new Set(['xalor.register']),
    };
  }

  // 📦 METADATA REDUCTION PASS
  // Pre-sort keys to guarantee clean git-diff generation order
  const orderedApiKeys = Object.keys(categoryStore).sort();

  // ========================================================================
  // 1. BUILD CONSTANTS STRINGS
  // ========================================================================
  const triggerArraysBlock = orderedApiKeys
    .map((api) => {
      // Internal naming override to format 'validate' as 'VALIDATION' for constants block parity
      const nameKey = api === 'validate' ? 'VALIDATION' : api.toUpperCase();
      const triggers = Array.from(categoryStore[api].fullTriggers);
      return `/**
 * MASTER ${nameKey} MODES CONFIGURATION
 * @note AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 */
export const ${nameKey}_MODE_TRIGGERS = [
${triggers.map((t) => `  '${t}',`).join('\n')}
] as const;`;
    })
    .join('\n\n');

  const modeArraysBlock = orderedApiKeys
    .map((api) => {
      // Internal naming override to format 'validate' as 'VALIDATION' for constants block parity
      const nameKey = api === 'validate' ? 'VALIDATION' : api.toUpperCase();
      const modes = Array.from(categoryStore[api].rawModes);
      return `/**
 * RAW ${nameKey} STRATEGY SPECIFICATION MODES
 * @note AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 */
export const ${nameKey}_MODES = [
${modes.map((m) => `  '${m}',`).join('\n')}
] as const;`;
    })
    .join('\n\n');

  const sentryTriggersCollection = orderedApiKeys
    .map((api) => {
      const nameKey = api === 'validate' ? 'VALIDATION' : api.toUpperCase();
      return `  ...${nameKey}_MODE_TRIGGERS,`;
    })
    .join('\n');

  const sentryModesDictionary = orderedApiKeys
    .filter((api) => api !== 'register') // Exclude register from mapping utility matrix
    .map((api) => {
      const nameKey = api === 'validate' ? 'VALIDATION' : api.toUpperCase();
      return `  ${api}Xalor: ${nameKey}_MODE_TRIGGERS,`;
    })
    .join('\n');

  const constantsOutput = `// ------------------------------------------------------------------------
// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by scripts/generate-configs.ts
// ------------------------------------------------------------------------

import { ObjectUtils } from '../utils';
import type { TUnique } from '../types';

${triggerArraysBlock}

/**
 * SENTRY_TRIGGER_NAMES
 * Complete identifier matrix used by the compiler's static analysis layers.
 */
const RAW_SENTRY_TRIGGER_NAMES = [
${sentryTriggersCollection}
] as const;

export const SENTRY_TRIGGER_NAMES = RAW_SENTRY_TRIGGER_NAMES satisfies TUnique<
  typeof RAW_SENTRY_TRIGGER_NAMES
>;

/**
 * SENTRY_TRIGGER_MODES
 * Strategy taxonomy groupings partitioning tokens into operational buckets.
 */
export const SENTRY_TRIGGER_MODES = {
${sentryModesDictionary}
};

export const RUNTIME_TRIGGER_NAMES = ObjectUtils.keys(SENTRY_TRIGGER_MODES);

${modeArraysBlock}
`;

  // ========================================================================
  // 2. BUILD TYPES STRINGS
  // ========================================================================
  const typeUnionsBlock = orderedApiKeys
    .map((api) => {
      const uppercaseApi = api.toUpperCase();
      const capitalizedApi = api.charAt(0).toUpperCase() + api.slice(1);

      // Explicit overrides to match your requested naming specs
      let modeTypeName = `T${capitalizedApi}XalorModes`;
      if (api === 'validate') modeTypeName = 'TValidateXalorModes';
      if (api === 'generate') modeTypeName = 'TGenerateXalorModes';
      if (api === 'transform') modeTypeName = 'TTransformXalorModes';
      if (api === 'register') modeTypeName = 'TRegisterXalorModes';
      if (api === 'match') modeTypeName = 'TMatchXalorModes';

      const triggersArrayName =
        api === 'validate'
          ? 'VALIDATION_MODE_TRIGGERS'
          : `${uppercaseApi}_MODE_TRIGGERS`;
      const modesArrayName =
        api === 'validate' ? 'VALIDATION_MODES' : `${uppercaseApi}_MODES`;

      // Formats full trigger naming to use the exact specified output schemas
      let triggerTypeName = `T${capitalizedApi}Triggers`;
      if (api === 'validate') triggerTypeName = 'TValidationTriggers';

      return `export type ${triggerTypeName} = (typeof constants.${triggersArrayName})[number];

/**
 * ${modeTypeName}
 * 
 * ${capitalizedApi} List Modes
 * 
 * @see {@link FoundationalTypesDocs.${modeTypeName}}
 */
export type ${modeTypeName} = (typeof constants.${modesArrayName})[number];`;
    })
    .join('\n\n');

  const typesOutput = `// ------------------------------------------------------------------------
// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by scripts/generate-configs.ts
// ------------------------------------------------------------------------

import * as constants from './constants';

${typeUnionsBlock}

/**
 * Comprehensive master matrix of all valid trigger tokens.
 */
export type TSentryTriggerNames = (typeof constants.SENTRY_TRIGGER_NAMES)[number];

/**
 * Comprehensive master matrix of all valid parent execution runtime trigger category keys.
 */
export type TRuntimeTriggerName = (typeof constants.RUNTIME_TRIGGER_NAMES)[number];
`;

  // ========================================================================
  // 3. WRITE EMISSIONS BACK TO DISK
  // ========================================================================
  const outputDirs = [
    path.dirname(OUTPUT_CONFIG_PATH),
    path.dirname(OUTPUT_TYPE_PATH),
  ];

  outputDirs.forEach((dir) => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  });

  fs.writeFileSync(OUTPUT_CONFIG_PATH, constantsOutput, 'utf8');
  fs.writeFileSync(OUTPUT_TYPE_PATH, typesOutput, 'utf8');

  console.log(
    `✅ Automated dynamic collection complete!\n` +
      `  👉 Saved constants: ${OUTPUT_CONFIG_PATH}\n` +
      `  👉 Saved types:     ${OUTPUT_TYPE_PATH}`,
  );
}

generateMasterConfig();
